- vars:
    traefik_conf_path: "/etc/traefik/traefik.toml"
    traefik_conf_url: "{{ zk_http_url }}/{{ traefik_conf_path }}"

  block:
    - name: Upload Traefik conf in ZooKeeper
      znode:
        hosts: "{{ zk_host }}"
        name: "{{ traefik_conf_path }}"
        value: "{{ lookup('template', 'traefik/traefik.toml') }}"
        state: present

    - name: "Deploy Traefik Reverse Proxy"
      marathon:
        marathon_uri: "{{ marathon_uri }}"
        group_id: /core/traefik
        group_json:
          apps:
            - id: "router"
              cpus: 2
              mem: 512
              disk: 0
              instances: 2
              args:
                - "--logLevel=DEBUG"
                - "--configfile=/mnt/mesos/sandbox/traefik.toml"
              container:
                type: DOCKER
                docker:
                  image: "containous/traefik:58c786ca8c354a85e7667ade3ab0c859d5402078"
                  # image: stibbons31/traefik-workaround-marathon-bad-gateway:workaround_marathon_bad_gateway
                  network: "HOST"
                  privileged: true
                  parameters: "{{ docker_log_driver_parameters }}"
                  forcePullImage: true
                volumes:
                  - containerPath: "/log"
                    hostPath: "log"
                    mode: "RW"
              portDefinitions:
                - port: 80
                  hostPort: 80
                  protocol: "tcp"
                  name: "http"
                - port: 443
                  hostPort: 443
                  protocol: "tcp"
                  name: "https"
                - port: "{{ traefik_admin_port }}"
                  hostPort: "{{ traefik_admin_port }}"
                  protocol: "tcp"
                  name: "admin"
              env:
                https_proxy: "{{zk.proxy_env.https_proxy}}"
                HTTPS_PROXY: "{{zk.proxy_env.https_proxy}}"
                http_proxy: "{{zk.proxy_env.http_proxy}}"
                HTTP_PROXY: "{{zk.proxy_env.http_proxy}}"
                no_proxy: "{{zk.proxy_env.no_proxy}}"
                NO_PROXY: "{{zk.proxy_env.no_proxy}}"
                ALL_PROXY: "{{zk.proxy_env.ALL_PROXY}}"
              healthChecks:
                # Need recent version of marathon
                # - path: "/health"
                #   protocol: "HTTP"
                #   port: {{ traefik_admin_port }}
                #   gracePeriodSeconds: 300
                #   intervalSeconds: 60
                #   maxConsecutiveFailures: 3
              upgradeStrategy:
                minimumHealthCapacity: 0.4
                maximumOverCapacity: 0
              labels:
                traefik.enable: "false"
              constraints:
                - - hostname
                  - UNIQUE # GROUP_BY not applicable since using HOST network
                - - hostname
                  - LIKE
                  - tlsisbld127l.tl.{{ top_domain }}|tlsisbld125l.tl.{{ top_domain }}|tlsisbld013l.tl.{{ top_domain }}|tlsisbld014l.tl.{{ top_domain }}
              uris:
                  - "{{ traefik_conf_url }}"
                  - "{{ zk_http_url }}/certs/forestscribe.crt"
                  - "{{ zk_http_url }}/certs/forestscribe.key"
